# Configure Nginx
- name: Adds Basic Auth to Nginx
  hosts: servers
  become: true

  tasks:
    - name: Add a user to a password file and ensure permissions are set
      community.general.htpasswd:
        path: /etc/nginx/.htpasswd
        name: builtby
        password: howie
        owner: "{{ username }}"
        group: www-data
        mode: 0640

    - name: Restart the nginx systemd service
      ansible.builtin.systemd:
        state: restarted
        name: nginx
