# Generated by Django 4.2.5 on 2023-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sales",
            field=models.BooleanField(default=False, verbose_name="Sales Staff"),
        ),
        migrations.AddField(
            model_name="user",
            name="pipedrive_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="Sales Staff must also have an associated Pipedrive User ID",
                null=True,
                unique=True,
                verbose_name="Pipedrive User ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Administrator"),
        ),
    ]
