# Generated by Django 4.2.5 on 2023-10-16 16:38

import apps.core.forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sales_commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sales Staff may have a non-standard sales commission",
                max_digits=5,
                null=True,
                validators=[apps.core.forms.validators.percentage_validator],
                verbose_name="Sales Commission (%)",
            ),
        ),
    ]
